version: "3.8"

services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    ports:
      - "8081:8081"
    networks:
      - app-network

  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    name: app-network
    driver: bridge
